# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 280c0a74d1e2213b754c5c9015cdc6f46b7cd8651d5c5ca6b4566010142c008ac0a9daf008bc903bcae6ede717757c5150788b9c1b2b1d6fb31e70286bad10e8

test:
  secret_key_base: 851ad4179f6a9c75ac46b3aba8eabf7d0e7d47cdf168ef9056d10474e53d6c70db07a1fc3b49b5f11f9340fa76b78c62dbda235cbfcfcc4e963cd8f82416e6b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
